-- Restore UUID defaults to match current schema and avoid drift
ALTER TABLE `Faq`
  MODIFY `id` VARCHAR(191) NOT NULL DEFAULT (uuid()),
  MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `FaqCategory`
  MODIFY `id` VARCHAR(191) NOT NULL DEFAULT (uuid());

ALTER TABLE `Partner`
  MODIFY `id` VARCHAR(191) NOT NULL DEFAULT (uuid());

ALTER TABLE `Rendezvous`
  MODIFY `id` VARCHAR(191) NOT NULL DEFAULT (uuid());
